# Generated by Django 2.2.1 on 2019-05-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing_test', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('c1', models.CharField(default='', max_length=200)),
                ('c2', models.CharField(default='', max_length=200)),
                ('c3', models.CharField(default='', max_length=200)),
                ('c4', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='c1', max_length=200)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=512)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('current_que_id', models.IntegerField(default=1)),
                ('first_login', models.BooleanField(default=False)),
                ('que_array', models.TextField(default='', null=True)),
                ('ans_array', models.TextField(default='', null=True)),
                ('test_progress', models.TextField(default='', null=True)),
                ('test_submitted', models.IntegerField(default=0)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Contestant')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Test')),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.User'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Test')),
            ],
        ),
    ]
